#!/usr/bin/bash

getProcessorsNumber () { 
local returnValue
#returnValue=$(grep -c ^processor /proc/cpuinfo)
returnValue=$(awk '/^processor/ {count++}END{print count}' /proc/cpuinfo)
echo "The number of available processors is: $returnValue"    
}

openFilesFunc () {
local returnValue
returnValue=$(ulimit -n)
echo "The maximum number of open files allowed for this user is: $returnValue"
}

fileSearch () { 
if [ -z "$SOURCE" -o  -z "$DESTINATION" ]; then
    echo "This option requires exactly TWO arguments."
    exit 0
fi
local queryResult
queryResult=$(find . ~/ -name "$SOURCE")
if [ -n "$queryResult" ]; then
    if [ -d "$DESTINATION" ]; then
        for item in $queryResult
        do
            cp -v "$item" "$DESTINATION"
        done
        return
    fi
    mkdir $DESTINATION
    for item in $queryResult
    do
        cp -v "$item" "$DESTINATION"
    done
fi
}
SOURCE=
DESTINATION=
while getopts “pob:” OPTION
do
    case $OPTION in
        p) getProcessorsNumber;;
        o) openFilesFunc;;
        b) SOURCE=$OPTARG
           eval "DESTINATION=\$$((OPTIND))"
           fileSearch;;
    esac
done
