#!/usr/bin/env bash


freememorycheck () {
local returnValue=$(free -m | awk 'FNR == 2{print $3'})
echo "The amount of free memory available is: $returnValue megabytes." 
 }

diskusagecheck () {
df -h 2>/dev/null | awk  '{print $1"\t\t" $4"\t"}' | column -t | less
}

quotacheck () {
local returnValue=$(quota 2>/dev/null)
echo $returnValue
}

groupscheck () {
local returnValue=$(groups)
echo $returnValue
}

historycheck () {
local returnValue=$(bash -i <<< 'history')
echo $returnValue | less
}

if [[ $# -eq 0 || $# -gt 1 ]]; then
        echo 'Error: the script requires exactly ONE argument.'
        exit 0
fi

selected_option=$1

case $selected_option in
        "freemem") freememorycheck;;
        "diskfree") diskusagecheck;;
        "quota") quotacheck;;
        "groups") groupscheck;;
        "history") historycheck;;
esac
