#!/bin/bash
# A menu driven shell script 
## ----------------------------------
# Step #1: Define variables
# ----------------------------------
EDITOR=vim
PASSWD=/etc/passwd
RED='\033[0;41;30m'
STD='\033[0;0;39m'
 
# ----------------------------------
# Step #2: User defined function
# ----------------------------------
pause(){
  read -p "Press [Enter] key to continue..." fackEnterKey
}
# load the basic menu
one(){
while true
do
 
	show_basic_menu
	read_basic_options
done
}
 
#load the advanced menu
two(){
	echo "two() called"
        pause
}

three(){
    echo ""

}
 
# function to display menus
show_main_menu() {
	clear
	echo "####################################"
	echo "#"	
	echo "# Welcome to System Manager"
	echo "# -------------------------"
	echo "# 1) basic menu options"
	echo "# 2) advanced menu options"
	echo "# 3) passwd file options"
	echo "# 4) quit"
}

show_basic_menu() {
	clear
	echo "####################################"
	echo "#"	
	echo "# Basic Tasks Menu"
	echo "# -------------------------"
	echo "# 1) Show free memory"
	echo "# 2) Show free disk space"
	echo "# 3) Show disk quota"
    echo "# 4) Show the groups I am a member of"
    echo "# 5) Show the history of commands for bash"
	echo "# 6) return to the Main Menu"
}
# read input from the keyboard and take a action
# invoke the one() when the user select 1 from the menu option.
# invoke the two() when the user select 2 from the menu option.
# Exit when user the user select 3 form the menu option.
read_main_options(){
	local choice
	read -p "Please enter a choice [1 - 4]" choice
	case $choice in
		1) one ;;
		2) two ;;
        3) three;;
		4) exit 0;;
		*) echo -e "${RED}Error...${STD}" && sleep 2
	esac
}
 
read_basic_options(){
	local choice
	read -p "Please enter a choice [1 - 6]" choice
	case $choice in
		1) basic_one ;;
		2) basic_two ;;
        3) basic_three;;
        4) basic_four;;
		5) basic_five;;
        6) exit 0;;
		*) echo -e "${RED}Error...${STD}" && sleep 2
	esac


}

 
read_advanced_options(){
	local choice
	read -p "Please enter a choice [1 - 6]" choice
	case $choice in
		1) advanced_one ;;
		2) advanced_two ;;
        3) advanced_three;;
        4) exit 0;;
		*) echo -e "${RED}Error...${STD}" && sleep 2
	esac


}


# ----------------------------------------------
# Trap CTRL+C, CTRL+Z and quit singles
# ----------------------------------------------
trap '' SIGINT SIGQUIT SIGTSTP
 
# -----------------------------------
# Main logic - infinite loop
# ------------------------------------
while true
do
 
	show_main_menu
	read_main_options
done
